### ISSUE TITLE
Feature: Allow for passive listen mode

### ISSUE THREAD

**Issue by gmolinsm** [aicodix/rattlegram#16]
It would be nice to have an option for the app to listen passively to incoming messages. Right now the app will not register any messages if the screen is off, which beats the purpose of messaging as opposed to talking directly.

**Comment by xdsopl** [comment]
Thank you for the suggestion. We would like to have that feature too, but Google decided to make it extremely hard to put apps into background, especially for audio apps because of security concerns. We would have to write a lot of code and have to support it too, because Google likes to constantly change things around. Our time is very limited and this is a free, open source app, so we really can't commit to even more time consuming changes. If someone want's to give it a go and implement it, we would of course review the changes and if we like them, merge the pull request.

**Comment by gmolinsm** [comment]
Hi @xdsopl. I can imagine this to be the case. Love the work you guys are putting into this app, it is truly a great thing. If I find some spare time, I will introduce these changes myself. Keep up the good work. Best
